import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Поле зрения</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Упражнение «Поле зрения» </h1>
      <h2>Макет:</h2>
      <h3>https://www.figma.com/file/IvCMZvlNYd1ApufgIseJxE/%D0%9F%D0%BE%D0%BB%D0%B5-%D0%B7%D1%80%D0%B5%D0%BD%D0%B8%D1%8F?node-id=0%3A1</h3>
      <p>Слова показывается на экране на одном уровне, но разделяются на две части. Между первой частью слова и второй делается разделение (пробел). </p>
      <p>Требуется возможность устанавливать настройки отображения слов: </p>
      <ul>
        <li>Сколько слов будет показываться за один цикл игры.</li>
        <li>В каждом новом цикле игры порядок слов должен быть случайным.</li>
        <li>Сколько букв будет в показываемых словах в течение цикла игры. Количество букв от 3 до 16. </li>
        <li>Необходимо настраивать скорость отображения (время появления) слова на экране. 1-5 секунд с шагом 0,5. </li>
      </ul>
      <p>Слова, которые будут использоваться в приложении, находятся в файле data/basa.json</p>
      <p >
        Решение задания находится по следующей <Link href = "/play" > ССЫЛКЕ</Link>
      </p>
      <footer className={styles.footer}>       
          Задание фирмы Сириус        
      </footer>
    </div>
  )
}
